### ISSUE TITLE
Cannot convert YAML with boolean key to JSON

### ISSUE THREAD

**Issue by kevinoid** [remarshal-project/remarshal#38]
Converting YAML with a boolean key to JSON works when it is the only key:

    $ printf 'on: Test\n' | yaml2json
    {"true":"Test"}

However, it fails when there is more than one key:

    $ printf 'on: Test\nother: Test\n' | yaml2json
    Error: Cannot convert data to JSON ('<' not supported between instances of 'str' and 'bool')

An example where this occurs is [GitHub Actions Workflows](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions) which contain the key [`on`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on), such as [an example from their documentation](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow) 

```yaml
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
```

It would be nice if remarshal could support converting these YAML files.
