### ISSUE TITLE
YAML null values missing after 0.18.0

### ISSUE THREAD

**Issue by mweinelt** [remarshal-project/remarshal#51]
One of our test cases in nixpkgs uses `yaml2yaml` to test a fixture that should stay the same.

```yaml
attrs:
  foo: null
'false': false
float: 3.141
list:
- null
- null
'null': null
path: /nix/store/xakpn1b34c5rrq97xnmqrmj2bpz2jfv9-formats.nix
str: foo
'true': true
```

With 0.18.0 and later all `null` values have gone missing. I'm not well versed in YAML unfortunately, so I have to ask whether this is fine or a regression.

```yaml
attrs:
  foo:
'false': false
float: 3.141
list:
- 
- 
'null':
path: /nix/store/xakpn1b34c5rrq97xnmqrmj2bpz2jfv9-formats.nix
str: foo
'true': true
```
