### ISSUE TITLE
set inside an array not converting correctly to TOML

### ISSUE THREAD

**Issue by HeitorAugustoLN** [remarshal-project/remarshal#56]
Just an example

JSON:
```json
{
  "language": [
    {
      "language": {
        "a": true
      },
      "name": "scheme"
    }
  ]
}
```

is generating:

```toml
[[language]]
name = "scheme"

[language.language]
a = true
```

It should be generating:

```toml
[[language]]
name = "scheme"
language = { a = true }
```
